Add deploy/api script

diff --git a/deploy/api b/deploy/api
--- a/deploy/api
+++ b/deploy/api
@@ -1,2 +1,45 @@
 #!/usr/bin/env bash
-set -e
+set -eo pipefail
+
+source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"
+
+ARCHIVE_FILE="/tmp/memoir.tar.gz"
+
+main() {
+  local host="$1"
+
+  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
+  [[ ! -e "$ARCHIVE_FILE" ]] && echo "Error: missing archive $ARCHIVE_FILE" && exit 1
+
+  belt_begin_session "root" "$host"
+
+  echo "Uploading app archive..."
+  app_upload "$ARCHIVE_FILE"
+
+  echo "Stopping memoir..."
+  systemd_unit_stop "memoir"
+
+  echo "Setting up memoir user..."
+  user_add "memoir"
+
+  echo "Copying files..."
+  app_copy_file "dist/memoir"
+  app_copy_file "memoir.env"
+
+  echo "Setting up permissions..."
+  app_set_permissions "memoir:memoir"
+
+  echo "Copying memoir unit file..."
+  systemd_add_unit "memoir.service"
+
+  echo "Starting memoir..."
+  systemd_unit_start "memoir"
+
+  echo "Adding caddy vhost..."
+  app_add_caddy_vhost
+
+  echo "Restarting caddy..."
+  caddy_restart
+}
+
+main "$1"
