Update deploy script to deploy app and admin frontends

diff --git a/deploy/frontend b/deploy/frontend
--- a/deploy/frontend
+++ b/deploy/frontend
@@ -5,12 +5,15 @@ BELT_ENV_TOOLBOX_TOOLS="caddy"
 
 source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"
 
-ARCHIVE_FILE="/tmp/memoir-app.tar.gz"
-
 main() {
-  local host="$1"
+  local app="$1"
+  local host="$2"
 
+  [[ -z "$app" ]] && echo "Error: missing argument app" && exit 1
   [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
+
+  ARCHIVE_FILE="/tmp/memoir-$1.tar.gz"
+
   [[ ! -e "$ARCHIVE_FILE" ]] && echo "Error: missing archive $ARCHIVE_FILE" && exit 1
 
   belt_begin_session "root" "$host"
@@ -36,5 +39,5 @@ main() {
   echo "OK"
 }
 
-echo "=> Deploying memoir-app"
-main "$1"
+echo "=> Deploying memoir frontend $1"
+main "$1" "$2"
